spring:
  datasource:
    hikari:
      jdbc-url: jdbc:mariadb://localhost:3306/muin?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
      driver-class-name: org.mariadb.jdbc.Driver
      username: root
      password: mariadb
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
    defer-datasource-initialization: true #Spring Boot 2.5 변경사항
  sql:
    init:
      mode: always